version: '3.1'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=rufet
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db
    # restart: always